### ISSUE TITLE
Classes might not be necessary

### ISSUE THREAD

**Issue by oliverjam** [fac25/Alex-Sumithra-Testing-TodoList#18]
It's cool that you're experimenting with JS `class` and object-oriented style programming. Just make sure you don't overcomplicate things/make it harder for yourself.

JS classes are pretty much just a way to dynamically create objects. However most of your classes are not dynamic—all their methods are static and they don't have constructors. Since you only ever use them once, and they have no internal state that might change, you could replace them with simple object literals and get the same behaviour in less/simpler code. For example

```js
class UI {
  static displayTasks() {}

  static addTaskToList(task) {}

  static deleteTask(element) {}

  static clearFields() {}
}
```

could be replaced with:

```js
const UI = {
  displayTasks() {},
  addTaskToList(task) {},
  deleteTask(element) {},
  clearFields() {},
}
```

This is a nice way to group related behaviour and methods together without needing the overhead of a `class`.

Even if you do need a small about of dynamic behaviour, like this one:

```js
class Task {
  constructor(title) {
    this.title = title;
  }
}
```
you could probably simplify by just using a function:

```js
function Task(title) {
  return { title };
}
```

However since there's not much point in creating this object with a single property you could skip it entirely and just use the title directly when you add a task to the store/UI.

**Comment by Sumithra-Suresh** [comment]
Thanks for pointing out. We have impelemented the changes as suggested.
